[tool.poetry]
name = "runme"
version = "0.2.0"
description = ""
authors = ["mkerostasia <mkerostasia@idealintegrations.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
