name: Running a script
on: push

jobs:
  run-a-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: lets check what directory we're in
        run: ls -la 
      - name: Run the script, no output.
        run: ./runme.sh 'an-argument'
      - name: run script with Github Output.  Must be key=value pairs.
        id: script_results
        run: echo "results=$(echo ./runme.sh 'to-output')" >> $GITHUB_OUTPUT
      - name: Use defined outputs to add to step summary
        env:
          LAST_RESULT: ${{  steps.script_results.results  }}
        run: |
          # Since this occurs in a different "environment" context variables
          # Must be explicitly added to the environment
          echo $LAST_RESULT >> $GITHUB_STEP_SUMMARY 
