name: Running a script
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lets check what directory we're in
        run: ls -la 
      - name: Run the script, no output.
        run: ./scripts/runme.sh 'an-argument'
      - name: run script with Github Output.  Must be key=value pairs.
        run: echo "myscript_results=$(./scripts/runme.sh 'to-output')" >> $GITHUB_OUTPUT
