name: Running a script
on: push

jobs:
  run-a-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the script, no output.
        run: scripts/runme.sh 'an-argument'


      - name: run script with Github Output.  Must be key=value pairs.
        id: script_results
        run: echo "results=$(scripts/runme.sh 'to-output')" >> $GITHUB_OUTPUT
      - name: Use defined outputs to add to step summary
        env:
          LAST_RESULT: ${{  steps.script_results.outputs.results  }}
        run: |
          # Since this occurs in a different "environment" context variables
          # Must be explicitly added to the environment
          echo $LAST_RESULT >> $GITHUB_STEP_SUMMARY
  review:
    runs-on: ubuntu-latest
    needs: [run-a-script]
    steps:
      - uses: actions/checkout@v4
      - name: Run the script, no output.
        run: scripts/runme.sh 'an-argument'
