name: Running a script
on: push

jobs:
  run-a-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: lets check what directory we're in
        run: ls -la 
      - name: Run the script, no output.
        run: ./runme.sh 'an-argument'
      - name: run script with Github Output.  Must be key=value pairs.
        run: echo "myscript_results=$(./runme.sh 'to-output')" >> $GITHUB_OUTPUT
